services:
  db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Schema
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: